using Texty.AI;
using Texty.Core.Interfaces;
using Texty.Integrations;
using Texty.OutlookAddin;
using Texty.Runtime.Clipboard;
using Texty.Runtime.Services;
using Texty.Runtime.Triggering;

namespace Texty.Runtime.Bootstrap;

public sealed record TextyRuntimeContext(
    ISnippetRepository SnippetRepository,
    IFolderRepository FolderRepository,
    IVersionRepository VersionRepository,
    ITrashRepository TrashRepository,
    ISnippetSearchIndex SearchIndex,
    ITriggerProvider HotkeyTriggerProvider,
    ITriggerEvaluator TriggerEvaluator,
    HotkeyInsertionService HotkeyInsertionService,
    ITemplateRenderer TemplateRenderer,
    IFormSchemaValidator FormSchemaValidator,
    IInsertionPipeline InsertionPipeline,
    IExternalDataResolverFactory ExternalResolverFactory,
    IAiProvider DefaultAiProvider,
    ITranslationProvider DefaultTranslationProvider,
    AiProviderRegistry AiProviders,
    TranslationProviderRegistry TranslationProviders,
    IMacroEngine MacroEngine,
    IMacroActionExecutor MacroActionExecutor,
    IPowerShellActionRunner PowerShellActionRunner,
    IAuditLogger AuditLogger,
    IAuthContextProvider AuthContextProvider,
    IRolePolicyService RolePolicyService,
    ILicenseService LicenseService,
    ISecretProtector SecretProtector,
    ISyncOrchestrator SyncOrchestrator,
    SnippetMaintenanceService SnippetMaintenanceService,
    SnippetVersioningService SnippetVersioningService,
    ISnippetWorkflowService SnippetWorkflowService,
    DocumentGeneratorService DocumentGeneratorService,
    TextCorrectionService TextCorrectionService,
    ClipboardHistoryService ClipboardHistoryService,
    ProductivityStatsService ProductivityStatsService,
    OutlookAddinBridge OutlookAddinBridge,
    FileImportService ImportService);
